/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.mvnfirst;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author zulfahmi
 */
public class ExchangeApplication extends javax.swing.JFrame {

    Currency sourceCurrency;
    Currency targetCurrency;
    ExchangeRates xRates;

    public ExchangeApplication() {
        getComboboxData();
        setExchangeFromWebServices();
        initComponents();
    }

    private Map<String, String> getCurrencyFromWebServices() {
        RestTemplate restTemplate = new RestTemplate();
        Map<String, String> curMap = restTemplate.getForObject("https://openexchangerates.org/api/currencies.json", Map.class);
        return curMap;
    }

    private List<Currency> toList() {
        List<Currency> curList = new ArrayList<>();
        Map<String, String> curMap = getCurrencyFromWebServices();
        Set<String> keys = curMap.keySet();
        for (String key : keys) {
            curList.add(new Currency(key, curMap.get(key)));//Key disini untuk mengammbil nilai and
//            System.out.println(key);
        }
        return curList;
    }

    private DefaultComboBoxModel getComboboxData() {
        List<Currency> curList = toList();
        return new DefaultComboBoxModel(curList.toArray());
    }

    private void setExchangeFromWebServices() {
        RestTemplate restTemplate = new RestTemplate();
        this.xRates = restTemplate.getForObject("https://openexchangerates.org/api/latest.json?app_id=a309fcfe3c2e410e8d3a886b75d3272e&base=USD", ExchangeRates.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromCombobox = new javax.swing.JComboBox<>();
        toCombobox = new javax.swing.JComboBox<>();
        sourceTextField = new javax.swing.JTextField();
        targetTextField = new javax.swing.JTextField();
        convertButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" Selected Currency "));

        jLabel1.setText("From Currency: ");

        jLabel2.setText("To Currency: ");

        fromCombobox.setModel(getComboboxData());
        fromCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromComboboxActionPerformed(evt);
            }
        });

        toCombobox.setModel(getComboboxData());
        toCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toComboboxActionPerformed(evt);
            }
        });

        targetTextField.setEditable(false);

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromCombobox, 0, 146, Short.MAX_VALUE)
                    .addComponent(toCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(targetTextField)
                    .addComponent(sourceTextField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fromCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(toCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(convertButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EXCHANGE CURRENCY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromComboboxActionPerformed
        JComboBox fromCB = (JComboBox) evt.getSource();
        sourceCurrency = (Currency) fromCB.getSelectedItem();
        System.out.println("Source Currency: " + sourceCurrency);
    }//GEN-LAST:event_fromComboboxActionPerformed

    private void toComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toComboboxActionPerformed
        JComboBox toCB = (JComboBox) evt.getSource();
        targetCurrency = (Currency) toCB.getSelectedItem();
        System.out.println("Target Currency: " + targetCurrency);
    }//GEN-LAST:event_toComboboxActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // LOGIC INI BISA DIJADIKAN METHOD
        Double sourceValue = Double.parseDouble(sourceTextField.getText());
        Double sourceRate = xRates.getRates().get(sourceCurrency.getCurrencyCode()); // NILAI SOURCE PER 1 USD
        Double targetRate = xRates.getRates().get(targetCurrency.getCurrencyCode()); // NILAI TARGET PER 1 USD
        Double baseValue = sourceValue / sourceRate;  // NILAI UANG YANG DIINPUT DALAM USD
        Double targetValue = baseValue * targetRate; // USD KITA KONVERSI KE MATA UANG TARGET. SELESAI

        // AGAR TAMPILAN LEBIH BAGUS
        DecimalFormat dnf = (DecimalFormat) NumberFormat.getCurrencyInstance();
        dnf.applyPattern("###,###.##");
        String formattedValue = dnf.format(targetValue);
        targetTextField.setText(formattedValue);
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExchangeApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JComboBox<String> fromCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sourceTextField;
    private javax.swing.JTextField targetTextField;
    private javax.swing.JComboBox<String> toCombobox;
    // End of variables declaration//GEN-END:variables
}
